
export const metadata = {
    title: "Vendor Dashboard",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return (
        <body>
            {children}
        </body>
    );
}
